In [1]:
import pandas as pd
import numpy as np

In [53]:
names =['DATE','TIME','CO_GT','PT08_S1_CO','NMHC_GT','C6H6_GT','PT08_S2_NMHC',
     'NOX_GT','PT08_S3_NOX','NO2_GT','PT08_S4_NO2','PT08_S5_O3','T','RH','AH', '1', '1']

df = pd.read_csv('../res/AirQualityUCI/AirQualityUCI.csv', sep=';', names=names)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9472 entries, 0 to 9471
Data columns (total 17 columns):
DATE            9358 non-null object
TIME            9358 non-null object
CO_GT           9358 non-null object
PT08_S1_CO      9358 non-null object
NMHC_GT         9358 non-null object
C6H6_GT         9358 non-null object
PT08_S2_NMHC    9358 non-null object
NOX_GT          9358 non-null object
PT08_S3_NOX     9358 non-null object
NO2_GT          9358 non-null object
PT08_S4_NO2     9358 non-null object
PT08_S5_O3      9358 non-null object
T               9358 non-null object
RH              9358 non-null object
AH              9358 non-null object
1               0 non-null float64
1.1             0 non-null float64
dtypes: float64(2), object(15)
memory usage: 1.2+ MB

/Users/perhunivan/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py:678: UserWarning: Duplicate names specified. This will raise an error in the future.
  return _read(filepath_or_buffer, kwds)

In [54]:
df

,DATE,TIME,CO_GT,PT08_S1_CO,NMHC_GT,C6H6_GT,PT08_S2_NMHC,NOX_GT,PT08_S3_NOX,NO2_GT,PT08_S4_NO2,PT08_S5_O3,T,RH,AH,1,1.1
0,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,NaN,NaN
1,10/03/2004,18.00.00,"2,6",1360,150,"11,9",1046,166,1056,113,1692,1268,"13,6","48,9","0,7578",NaN,NaN
2,10/03/2004,19.00.00,2,1292,112,"9,4",955,103,1174,92,1559,972,"13,3","47,7","0,7255",NaN,NaN
3,10/03/2004,20.00.00,"2,2",1402,88,"9,0",939,131,1140,114,1555,1074,"11,9","54,0","0,7502",NaN,NaN
4,10/03/2004,21.00.00,"2,2",1376,80,"9,2",948,172,1092,122,1584,1203,"11,0","60,0","0,7867",NaN,NaN
5,10/03/2004,22.00.00,"1,6",1272,51,"6,5",836,131,1205,116,1490,1110,"11,2","59,6","0,7888",NaN,NaN
6,10/03/2004,23.00.00,"1,2",1197,38,"4,7",750,89,1337,96,1393,949,"11,2","59,2","0,7848",NaN,NaN
7,11/03/2004,00.00.00,"1,2",1185,31,"3,6",690,62,1462,77,1333,733,"11,3","56,8","0,7603",NaN,NaN
8,11/03/2004,01.00.00,1,1136,31,"3,3",672,62,1453,76,1333,730,"10,7","60,0","0,7702",NaN,NaN
9,11/03/2004,02.00.00,"0,9",1094,24,"2,3",609,45,1579,60,1276,620,"10,7","59,7","0,7648",NaN,NaN
10,11/03/2004,03.00.00,"0,6",1010,19,"1,7",561,-200,1705,-200,1235,501,"10,3","60,2","0,7517",NaN,NaN
11,11/03/2004,04.00.00,-200,1011,14,"1,3",527,21,1818,34,1197,445,"10,1","60,5","0,7465",NaN,NaN
12,11/03/2004,05.00.00,"0,7",1066,8,"1,1",512,16,1918,28,1182,422,"11,0","56,2","0,7366",NaN,NaN
13,11/03/2004,06.00.00,"0,7",1052,16,"1,6",553,34,1738,48,1221,472,"10,5","58,1","0,7353",NaN,NaN
14,11/03/2004,07.00.00,"1,1",1144,29,"3,2",667,98,1490,82,1339,730,"10,2","59,6","0,7417",NaN,NaN
15,11/03/2004,08.00.00,2,1333,64,"8,0",900,174,1136,112,1517,1102,"10,8","57,4","0,7408",NaN,NaN
16,11/03/2004,09.00.00,"2,2",1351,87,"9,5",960,129,1079,101,1583,1028,"10,5","60,6","0,7691",NaN,NaN
17,11/03/2004,10.00.00,"1,7",1233,77,"6,3",827,112,1218,98,1446,860,"10,8","58,4","0,7552",NaN,NaN
18,11/03/2004,11.00.00,"1,5",1179,43,"5,0",762,95,1328,92,1362,671,"10,5","57,9","0,7352",NaN,NaN
19,11/03/2004,12.00.00,"1,6",1236,61,"5,2",774,104,1301,95,1401,664,"9,5","66,8","0,7951",NaN,NaN
20,11/03/2004,13.00.00,"1,9",1286,63,"7,3",869,146,1162,112,1537,799,"8,3","76,4","0,8393",NaN,NaN
21,11/03/2004,14.00.00,"2,9",1371,164,"11,5",1034,207,983,128,1730,1037,"8,0","81,1","0,8736",NaN,NaN
22,11/03/2004,15.00.00,"2,2",1310,79,"8,8",933,184,1082,126,1647,946,"8,3","79,8","0,8778",NaN,NaN
23,11/03/2004,16.00.00,"2,2",1292,95,"8,3",912,193,1103,131,1591,957,"9,7","71,2","0,8569",NaN,NaN
24,11/03/2004,17.00.00,"2,9",1383,150,"11,2",1020,243,1008,135,1719,1104,"9,8","67,6","0,8185",NaN,NaN
25,11/03/2004,18.00.00,"4,8",1581,307,"20,8",1319,281,799,151,2083,1409,"10,3","64,2","0,8065",NaN,NaN
26,11/03/2004,19.00.00,"6,9",1776,461,"27,4",1488,383,702,172,2333,1704,"9,7","69,3","0,8319",NaN,NaN
27,11/03/2004,20.00.00,"6,1",1640,401,"24,0",1404,351,743,165,2191,1654,"9,6","67,8","0,8133",NaN,NaN
28,11/03/2004,21.00.00,"3,9",1313,197,"12,8",1076,240,957,136,1707,1285,"9,1","64,0","0,7419",NaN,NaN
29,11/03/2004,22.00.00,"1,5",965,61,"4,7",749,94,1325,85,1333,821,"8,2","63,4","0,6905",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9443,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9447,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9451,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN